### ISSUE TITLE
Converting object to an encodable object failed: Instance of 'Call'

### ISSUE THREAD

**Issue by vxern** [gavanitrate/faunadb-http-dart#16]
I have tried the `call` function in several ways, and all return the same exception:

```
Converting object to an encodable object failed: Instance of 'Call'     
#0      _JsonStringifier.writeObject (dart:convert/json.dart:688:7)     
#1      _JsonStringStringifier.printOn (dart:convert/json.dart:877:17)  
#2      _JsonStringStringifier.stringify (dart:convert/json.dart:862:5)
#3      JsonEncoder.convert (dart:convert/json.dart:262:30)
#4      JsonCodec.encode (dart:convert/json.dart:172:45)
#5      Expr.toString (package:faunadb_http/src/fql/expr.dart:49:17)
#6      print (dart:core/print.dart:9:24)
```

This is the code:

```
Call(
  Function_('createUser'),
  arguments: [
    username,
    email,
    password,
    generateVerificationCode(),
  ],
);
```

This did not work, so I tried using `Obj`. This does not work either

```
Call(
  Function_('createUser'),
  arguments: Obj([
    username,
    email,
    password,
    generateVerificationCode(),
  ]),
);
```

Neither does

```
Call(
  Function_('createUser'),
  arguments: Obj({
    'username': username,
    'email': email,
    'password': password,
    'verificationCode': generateVerificationCode(),
  }),
);
```

Am I doing something wrong?

**Comment by gavanitrate** [comment]
Your first code block should be the correct way calling a UDF.
I'm assuming the UDF works through the Fauna Shell and was created in a way like this.
```
CreateFunction(Obj({
   'name': 'add-two-nums',
   'body': Query(Lambda(['x', 'y'], Add([Var('x'), Var('y')])))
}))
```
Also any chance `generateVerificationCode` is not returning the correct type? i.e. `Future` or something like that?

**Comment by vxern** [comment]
It is indeed. My bad!
